### ISSUE TITLE
need more info

### ISSUE THREAD

**Issue by 555tr** [RyderL/Wargame-RCON#1]
![image](https://user-images.githubusercontent.com/110760205/183621989-97fa5562-9ebe-42f1-8d4e-9165e2878613.png)
Can you tell me how to install it in detail,and what environments must need to install? I installed node and yarn, but he still reported an error. Is the configuration of config.js wrong?
![image](https://user-images.githubusercontent.com/110760205/183623004-a9c532ce-cba2-40bc-96bc-8f7bf14d7034.png)

**Comment by carcigenicate** [comment]
The fix would be either of:

```javascript
setTimeout(async () => { 
    await savePlayerInfo(req.host, {id: params.id, name: newName, flag: 1});
    global.cache[host].rcon.send(`setpvar ${params.id} PlayerName ${newName}`); 
}, 300);

// Or

setTimeout(() => { 
    savePlayerInfo(req.host, {id: params.id, name: newName, flag: 1})
        .then(() => {
            global.cache[host].rcon.send(`setpvar ${params.id} PlayerName ${newName}`); 
        });

}, 300);
```

`replace` should also probably be explicitly creating a promise though. It doesn't make much sense for the function to be marked as `async`, then not wait on any promises. This would be a bit better I think:

```javascript
const replace = function(host, params) {
  return new Promise((resolve, reject) => {
    for(let item of replacement.source) {
      if(params.name.toLowerCase().indexOf(item) > -1) {
        let newName = replacement.target[Math.floor(Math.random() * replacement.target.length)]
        setTimeout(async () => {
          await savePlayerInfo(req.host, {id: params.id, name: newName, flag: 1});
          global.cache[host].rcon.send(`setpvar ${params.id} PlayerName ${newName}`);
        }, 300);
        setTimeout(() => {
          broadcastPlayerList(host);
          resolve();
        }, 1000);
      }
    }
  });
}
```

And then code calling `replace` should `await` the returned promise. Although their use of two `setTimeout`s still feels a bit sketchy.

**Comment by RyderL** [comment]
sry guys, this tool is mainly for my own convenience to manage my server, so there are often cases where new versions are not submitted to github, at present, this problem has been fixed, and i will continue to update some new features recently
