### ISSUE TITLE
Using local banned_clients.ini when globalBan = false

### ISSUE THREAD

**Issue by ddrahos** [RyderL/Wargame-RCON#3]
Hey,

I know previous versions of the RCON tool used the banned_clients.ini to record banned clients.

I don't use the globalBan option since I don't want to use your ban list.

Is there a way to back port the old ban system to use the banned_clients.ini when _globalBan = false_ in config.js?

Or how can I setup my own GlobalBanURL to use a local file so I can have a ban list separate from yours?

Just some admins of mine observed that the ban function didn't work and they were asking me to enter it manually in the banned_clients.ini.

Another issue I noticed is that the count down noise is not working currently. Very nice feature to have if you're alt-tabbed out of Wargame.

I've also gone into the index.js and fixed some of the map names which had typos or didn't match the Wargame in-game names, do you want me to send those?

**Comment by RyderL** [comment]
globalBan=true doesn't mean get ban list from my server, but for people with multiple servers.

**Comment by RyderL** [comment]
the possibility that the countdown does not work is that your config does not point to the working directory of the wrd server, coz this function needs to read the server log to work.

**Comment by RyderL** [comment]
you can send me the misspelled parts thx 👍

**Comment by RyderL** [comment]
btw, the reason for not using banned_clients.ini is that people who have been banned cannot be unbanned normally, and the content in the file must be deleted and the server restarted to take effect

**Comment by ddrahos** [comment]
Here is the section of the index.js that I spellchecked. There were some other typos I fixed and made to match Wargame's terminology in game.

`  maps: {
        // 1vs1
        "2x3_Esashi":{name: "Tropic Thunder", mode: 1},
        "2x3_Gangjin":{name: "Mud Fight !", mode: 1},    
        "2x3_Hwaseong":{name: "Nuclear winter is coming", mode: 1},
        "2x2_port_Wonsan_Terrestre":{name: "Wonsan harbour", mode: 1},
        "3x3_Muju":{name: "Plunjing Valley", mode: 1},
        "2x3_Montagne_1":{name: "Death Row", mode: 1},
        "5x3_Marine_1_small_Terrestre":{name: "Strait to the point (small)", mode: 1},
        "2x3_Tohoku_Alt":{name: "Paddy Field", mode: 1},
        "3x3_Muju_Alt":{name: "Punchbowl", mode: 1},
        "3x3_Marine_3_Reduite_Terrestre":{name: "Hell in a Very Small Place", mode: 1},
        "2x2_port_Wonsan":{name: "Wonsan harbor", mode: 1, water: 2},
        "4x4_Marine_6":{name: "Out of the blue", mode: 1, water: 1},
        "4x4_Marine_7":{name: "Standoff in Barents", mode: 1, water: 1},

        // 2vs2
        "2x3_Boseong":{name: "Apocalypse Imminent", mode: 2},
        "2x3_Tohoku":{name: "Paddy Field", mode: 2},
        "2x3_Anbyon":{name: "Hop and Glory", mode: 2},
        "3x2_Montagne_3":{name: "Chosin Reservoir", mode: 2},
        "3x2_Taebuko":{name: "Jungle LAW", mode: 2},
        "3x2_Haenam_Alt":{name: "Operation Chromite", mode: 2},
        "3x3_Highway_Small":{name: "Highway to Seoul", mode: 2},
        "3x2_Boryeong_Terrestre":{name: "Gunboat diplomacy", mode: 2},
        "3x3_Marine_3_Terrestre":{name: "Another D-Day in paradise ", mode: 2},
        "5x3_Marine_1_small":{name: "Strait to the point (small)", mode: 2, water: 2},
        "4x4_Marine_10":{name: "Alea Jacta West", mode: 2, water: 1},
        "4x4_Marine_9":{name: "Bulldogs and Vampires", mode: 2, water: 1},

        // 3vs3    
        "3x2_Sangju":{name: "Tough Jungle", mode: 3},
        "Chongju_Alt":{name: "Wrecks and Rocks", mode: 3},
        "3x2_Taean":{name: "Bloody Ridge", mode: 3},
        "2x3_Montagne_2":{name: "Cliff Hanger", mode: 3}, 
        "3x2_Haenam":{name: "Back to Inchon", mode: 3},
        "5x3_Marine_1_Terrestre":{name: "Strait to the point", mode: 3},
        "3x3_Pyeongtaek_Alt":{name: "38th Perpendicular", mode: 3},
        "3x3_Highway":{name: "Highway to Seoul", mode: 3},
        "3x3_Thuringer_Wald":{name: "Snake Pit", mode: 3},
        "3x3_Thuringer_Wald_Alt":{name: "Crossroads", mode: 3},
        "3x2_Boryeong":{name: "Gunboat diplomacy", mode: 3, water: 2},
        "3x3_Marine_3":{name: "Another D-Day in paradise", mode: 3, water: 2},
        "4x4_Marine_4":{name: "Atoll Inbound", mode: 3, water: 1},
        "4x4_Marine_5":{name: "Waterworld", mode: 3, water: 1},

        //4vs4
        "4x3_Sangju_Alt":{name: "The Green Mile", mode: 4},
        "5x3_Marine_1_Alt":{name: "Battle of Yuchalnok Pass", mode: 4},
        "3x3_Pyeongtaek":{name: "38th Parallel", mode: 4},
        "3x3_Montagne_4":{name: "A Maze in Japan", mode: 4},
        "3x3_Chongju":{name: "Korea Rocks", mode: 4},
        "3x3_Montagne_1":{name: "Cold War Z", mode: 4},`

**Comment by ddrahos** [comment]
Here's the spellchecked index.js, there were a few typos beyond the map list and I made sure that the names matched the game's terminology.

```
data: {
    mapping: {
      maps: {
        // 1vs1
        "2x3_Esashi":{name: "Tropic Thunder", mode: 1},
        "2x3_Gangjin":{name: "Mud Fight !", mode: 1},    
        "2x3_Hwaseong":{name: "Nuclear winter is coming", mode: 1},
        "2x2_port_Wonsan_Terrestre":{name: "Wonsan harbour", mode: 1},
        "3x3_Muju":{name: "Plunjing Valley", mode: 1},
        "2x3_Montagne_1":{name: "Death Row", mode: 1},
        "5x3_Marine_1_small_Terrestre":{name: "Strait to the point (small)", mode: 1},
        "2x3_Tohoku_Alt":{name: "Paddy Field", mode: 1},
        "3x3_Muju_Alt":{name: "Punchbowl", mode: 1},
        "3x3_Marine_3_Reduite_Terrestre":{name: "Hell in a Very Small Place", mode: 1},
        "2x2_port_Wonsan":{name: "Wonsan harbor", mode: 1, water: 2},
        "4x4_Marine_6":{name: "Out of the blue", mode: 1, water: 1},
        "4x4_Marine_7":{name: "Standoff in Barents", mode: 1, water: 1},
            
        // 2vs2
        "2x3_Boseong":{name: "Apocalypse Imminent", mode: 2},
        "2x3_Tohoku":{name: "Paddy Field", mode: 2},
        "2x3_Anbyon":{name: "Hop and Glory", mode: 2},
        "3x2_Montagne_3":{name: "Chosin Reservoir", mode: 2},
        "3x2_Taebuko":{name: "Jungle LAW", mode: 2},
        "3x2_Haenam_Alt":{name: "Operation Chromite", mode: 2},
        "3x3_Highway_Small":{name: "Highway to Seoul", mode: 2},
        "3x2_Boryeong_Terrestre":{name: "Gunboat diplomacy", mode: 2},
        "3x3_Marine_3_Terrestre":{name: "Another D-Day in paradise ", mode: 2},
        "5x3_Marine_1_small":{name: "Strait to the point (small)", mode: 2, water: 2},
        "4x4_Marine_10":{name: "Alea Jacta West", mode: 2, water: 1},
        "4x4_Marine_9":{name: "Bulldogs and Vampires", mode: 2, water: 1},
            
        // 3vs3    
        "3x2_Sangju":{name: "Tough Jungle", mode: 3},
        "Chongju_Alt":{name: "Wrecks and Rocks", mode: 3},
        "3x2_Taean":{name: "Bloody Ridge", mode: 3},
        "2x3_Montagne_2":{name: "Cliff Hanger", mode: 3}, 
        "3x2_Haenam":{name: "Back to Inchon", mode: 3},
        "5x3_Marine_1_Terrestre":{name: "Strait to the point", mode: 3},
        "3x3_Pyeongtaek_Alt":{name: "38th Perpendicular", mode: 3},
        "3x3_Highway":{name: "Highway to Seoul", mode: 3},
        "3x3_Thuringer_Wald":{name: "Snake Pit", mode: 3},
        "3x3_Thuringer_Wald_Alt":{name: "Crossroads", mode: 3},
        "3x2_Boryeong":{name: "Gunboat diplomacy", mode: 3, water: 2},
        "3x3_Marine_3":{name: "Another D-Day in paradise", mode: 3, water: 2},
        "4x4_Marine_4":{name: "Atoll Inbound", mode: 3, water: 1},
        "4x4_Marine_5":{name: "Waterworld", mode: 3, water: 1},
            
        //4vs4
        "4x3_Sangju_Alt":{name: "The Green Mile", mode: 4},
        "5x3_Marine_1_Alt":{name: "Battle of Yuchalnok Pass", mode: 4},
        "3x3_Pyeongtaek":{name: "38th Parallel", mode: 4},
        "3x3_Montagne_4":{name: "A Maze in Japan", mode: 4},
        "3x3_Chongju":{name: "Korea Rocks", mode: 4},
        "3x3_Montagne_1":{name: "Cold War Z", mode: 4},
        "3x3_Gangjin":{name: "Floods", mode: 4},
        "4x4_ThreeMileIsland":{name: "Sun of Juche", mode: 4},
        "4x4_ThreeMileIsland_Alt":{name: "Final Meltdown", mode: 4},
        "5x3_Marine_1":{name: "Strait to the point", mode: 4, water: 2},
        "3x3_Marine_2":{name: "Smoke in the water", mode: 4, water: 2},
        "4x3_Gjoll":{name: "Heartbreak Ridge", mode: 4},
        "3x3_Asgard":{name: "The Crown of Crags", mode: 4},
            
        //10vs10
        "5x3_Asgard_10v10":{name: "Asgard", mode: 10},
        "5x3_Gjoll_10v10":{name: "Gjoll", mode: 10},
        "4x4_Russian_Roulette":{name: "Russian Roulette", mode: 10}
      },
      gameMode: {
        1: "Destruction",
        2: "Siege",
        3: "Economy",
        4: "Conquest"
      },
      gameType: {
        0: "Confrontation",
        1: "BLUFOR",
        2: "REDFOR"
      },
      incomeRate: {
        0: "None",
        1: "Very low (-40%)",
        2: "Low (-20%)",
        3: "Medium",
        4: "High (+20%)",
        5: "Very high (+40%)"
      },
      thematic: {
        "-1": "No",
        "-2": "Any",
        "0": "Motorized",
        "1": "Armored",
        "2": "Support",
        "3": "Marine",
        "4": "Mechanized",
        "5": "Airborne",
        "6": "Naval"
      },
      thematicSeq: [-1, -2, 0, 1, 2, 3, 4, 5, 6],
      date: {
        "-1": "No",
        "0": "Post-85",
        "1": "Post-80"
      },
      dateSeq: [-1, 0, 1],
      nation: {
        "-1": "No",
        "0": "Nations and coalitions",
        "1": "Nations only",
        "2": "Coalitions only"
      },
      nationSeq: [-1, 0, 1, 2],
      nationCode: {
        blue: ["BLUFOR","US","UK","FRA","RFA","CAN","DAN","SWE","NOR","ANZ","JAP","ROK","HOL","ISR","SA","EURO","SCAND","CMW","BLUEDRAGONS","LAND","NORAD","NLGR"],
        red: ["REDFOR","RDA","USSR","POL","FIN","YUG","CZ","CHI","NK","NSWP","REDDRAGONS","FINPOL","YUGVAK"]
      },
      restrict: [-1, 0, 1, 2, 3, 4, 5],
      time: {
        "1": "1 Hour",
        "12": "12 Hours",
        "24": "1 Day",
        "72": "3 Days",
        "168": "1 Week",
        "336": "2 Weeks",
        "720": "1 Month",
        "1440": "2 Months",
        "2160": "3 Months",
        "4320": "6 Months",
        "0": "Permanent"
      }
    },
```

**Comment by ddrahos** [comment]
> the possibility that the countdown does not work is that your config does not point to the working directory of the wrd server, coz this function needs to read the server log to work.

I have it working correctly since the RCON client reads the server log and can read the chat and send the Prompt Message.

**Comment by ddrahos** [comment]
> globalBan=true doesn't mean get ban list from my server, but for people with multiple servers.

Okay I understand how it works now.
